version: '3.8'

services:
  app:
    image: node:20-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=${PORT:-3000}
      - STUN_URL=${STUN_URL:-stun:stun.l.google.com:19302}
      - TURN_URL=${TURN_URL}
      - TURN_USER=${TURN_USER}
      - TURN_PASS=${TURN_PASS}
      - RELAY_ONLY=${RELAY_ONLY:-false}
    ports:
      - "3000:3000"
    depends_on:
      - turn

  turn:
    image: coturn/coturn:latest
    restart: always
    command: ["-c", "/etc/coturn/turnserver.conf"]
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
    ports:
      - "3478:3478"
      - "3478:3478/udp"